language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  - docker tag udagram-frontend hieupt/udagram-frontend:v1
  - docker tag udagram-api-feed hieupt/udagram-api-feed:v1
  - docker tag udagram-api-user hieupt/udagram-api-user:v1
  - docker tag udagram-reverseproxy hieupt/udagram-reverseproxy:v1

after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push hieupt26/udagram-frontend:v1
- docker push hieupt26/udagram-api-feed:v1
- docker push hieupt26/udagram-api-user:v1
- docker push hieupt26/udagram-reverseproxy:v1